### ISSUE TITLE
maven打包出错

### ISSUE THREAD

**Issue by Anbool** [xtTech/app-version#8]
app-version-manager执行maven打包出现了这个错误，麻烦协助一下，谢谢。

![](https://i.30mo.com/2019/08/06/K8j.png)

**Comment by zoeminghong** [comment]
不好意思，之前是存在这个问题，你可以尝试一下，最新的 1.0.1 版本，直接执行 `build.sh / build.bat` 命令

**Comment by Anbool** [comment]
> 不好意思，之前是存在这个问题，你可以尝试一下，最新的 1.0.1 版本，直接执行 `build.sh / build.bat` 命令

谢谢回复，我已经下载了最新的1.0.1版本，执行了build.sh流程正常，但是最终app-version-manager打包出来的jar文件名是app-version-manager-1.0.1-RC.jar，我把/bin目录下的spring.sh文件放在了app-version-manager对的target目录，执行发现错误：

![](https://i.30mo.com/2019/08/07/fYM.png)

将app-version-manager-1.0.1-RC.jar更名为avm.jar，虽然流程成功，但实际服务没有启动。

![](https://i.30mo.com/2019/08/07/YyE.png)

哪里出问题吗？

**Comment by zoeminghong** [comment]
你需要基于 `spring.sh` 脚本文件，做相应的修改，jar 名称需要进行相应的替换，`-Dspring.profiles.active=dev` 也需要根据实际情况进行修改
![image](https://user-images.githubusercontent.com/10401743/62705346-cb5af880-ba1f-11e9-9768-06158feaae30.png)

**Comment by Anbool** [comment]
> 你需要基于 `spring.sh` 脚本文件，做相应的修改，jar 名称需要进行相应的替换，`-Dspring.profiles.active=dev` 也需要根据实际情况进行修改
> ![image](https://user-images.githubusercontent.com/10401743/62705346-cb5af880-ba1f-11e9-9768-06158feaae30.png)

![](https://i.30mo.com/2019/08/09/05u.png)

两个位置已经全部改了，但现在提示启动了实际还是没有运行唉............

![](https://i.30mo.com/2019/08/09/ZJN.png)

还有一个问题是在app-version-rest目录修改了spring.sh，执行./spring.sh avr-start没有作用

![](https://i.30mo.com/2019/08/09/rsO.png)

![](https://i.30mo.com/2019/08/09/gI6c.png)

执行./spring.sh avm-start可以生效，但仍然没有启动服务.........

![](https://i.30mo.com/2019/08/09/ggBn.png)

**Comment by Anbool** [comment]
@zoeminghong
哥哥，你在吗？我每天都在等待你得回复。

**Comment by zoeminghong** [comment]
你贴一下被你该动 spring.sh 我看到你的启动命令有点奇怪

**Comment by zoeminghong** [comment]
你微信号多少 我加你一下吧



    



    
    
    



    
        
            
                
                    
                        
                    
                    
                        
                            i
                            
                            
                                
                                    邮箱：i@zerostech.com
                                
                        
                    
                
            
        
    


Signature is customized by Netease Mail Master


            在2019年08月11日 21:41，Anbool 写道： @zoeminghong

哥哥，你在吗？我每天都在等待你得回复。



—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/xtTech/app-version/issues/8?email_source=notifications\u0026email_token=ACPLPTYDZUIYH2NVYVJJRD3QEAJI5A5CNFSM4IJVCHOKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD4BBEWI#issuecomment-520229465",

"url": "https://github.com/xtTech/app-version/issues/8?email_source=notifications\u0026email_token=ACPLPTYDZUIYH2NVYVJJRD3QEAJI5A5CNFSM4IJVCHOKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD4BBEWI#issuecomment-520229465",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by Anbool** [comment]
![](https://i.30mo.com/2019/08/12/g3uR.png)

![](https://i.30mo.com/2019/08/12/gDOP.png)

![](https://i.30mo.com/2019/08/12/gi8C.png)

![](https://i.30mo.com/2019/08/12/gj0S.png)

只有第一张图片做了一些修改，其他保持了默认，烦请查看一下，谢谢。@zoeminghong

**Comment by zoeminghong** [comment]
你不需要改动restart start stop这些case，这个本身是一个公共的，这么改了，缺少了通用性，你如果想要确认包是否有问题你可以 `nohup java -jar -Xms1024m -Xmx1024m -Xss512k -Dspring.profiles.active=dev ${JAR} > service.log 2>&1 &` 这样就可以了

**Comment by zoeminghong** [comment]
还有用户名就是我微信，可以加我
